// GET https://reqres.in/api/users

// OPTIONS https://reqres.in/api/users

// HEAD https://reqres.in/api/users

# POST https://restful.dev/wp-json/wp/v2/posts
# Authorization: Basic chris password
# Content-Type: application/json

# {
#     "title": "new post",
#     "content": "content of new post",
#     "status": "publish",
#     "author": 1
# }